using System.Text;
using System.Text.Encodings.Web;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Proudust.Web;

[Generator(LanguageNames.CSharp)]
public sealed partial class WebSerializerGenerator : IIncrementalGenerator
{
    internal const string WebSerializableAttributeFullName = "Proudust.Web.WebSerializableAttribute";

    internal const string WebSerializableAttributeTFullName = "Proudust.Web.WebSerializableAttribute`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("WebSerializableAttribute.g.cs", /* lang=c#-test */ """
                // <auto-generated/>
                #nullable enable

                using System;
                using System.Diagnostics;

                namespace Proudust.Web;

                [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
                [Conditional("COMPILE_TIME_ONLY")]
                internal sealed class WebSerializableAttribute : Attribute
                {
                    public WebSerializableAttribute(Type type)
                    {
                    }
                }

                [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
                [Conditional("COMPILE_TIME_ONLY")]
                internal sealed class WebSerializableAttribute<T> : Attribute;
                """);
        });

        var knownTypeSymbols = context.CompilationProvider
            .Select((compilation, _) => new KnownTypeSymbols(compilation));

        var isNet8OrGreater = context.ParseOptionsProvider
            .Select(static (parseOptions, _) => parseOptions.PreprocessorSymbolNames.Contains("NET8_0_OR_GREATER"));

        var nonGeneric = context.SyntaxProvider.ForAttributeWithMetadataName(
            WebSerializableAttributeFullName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (context, _) => (TypeDeclarationSyntax)context.TargetNode
        );

        var generic = context.SyntaxProvider.ForAttributeWithMetadataName(
            WebSerializableAttributeTFullName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (context, _) => (TypeDeclarationSyntax)context.TargetNode
        );

        // https://github.com/dotnet/roslyn/issues/74585#issuecomment-2260094810
        var typeDeclarations = nonGeneric
            .Collect()
            .Combine(generic.Collect())
            .SelectMany(static (tuple, _) => tuple.Left.AddRange(tuple.Right).Distinct());

        context.RegisterSourceOutput(typeDeclarations.Combine(knownTypeSymbols).Combine(isNet8OrGreater), static (context, source) =>
        {
            var ((typeDeclaration, knownSymbols), isNet8OrGreater) = source;

            if (!isNet8OrGreater)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.TargetFrameworkTooLow,
                    typeDeclaration.Identifier.GetLocation()));
                return;
            }

            var semanticModel = knownSymbols.Compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
            var typeSymbol = semanticModel.GetDeclaredSymbol(typeDeclaration, context.CancellationToken);
            if (typeSymbol is null)
            {
                return;
            }

            var sb = new StringBuilder();
            sb.Append(/* lang=c#-test */ """
                // <auto-generated/>
                #nullable enable

                using System.Runtime.CompilerServices;
                using Cysharp.Web;
                using Proudust.Web;

                """);

            var providerType = new ProviderType(typeSymbol, knownSymbols);
            if (providerType.Namespace is string ns)
            {
                sb.Append("namespace ").Append(ns).AppendLine(";");
            }
            sb.AppendLine();

            foreach (var (typeKeyword, name) in providerType.Parents)
            {
                sb.AppendLine($$"""
                    partial {{typeKeyword}} {{name}}
                    {
                    """);
            }

            sb.AppendLine($$"""
                partial class {{providerType.Name}} : IWebSerializerProvider
                {
                    public static IWebSerializerProvider Instance { get; } = new {{providerType.Name}}();

                    {{providerType.Name}}()
                    {
                    }

                    public IWebSerializer<T>? GetSerializer<T>()
                    {
                        return Cache<T>.Serializer;
                    }

                    private static class Cache<T>
                    {
                        public static IWebSerializer<T>? Serializer = null;
                    }

                    static {{providerType.Name}}()
                    {
                """);

            foreach (var type in providerType.TargetTypes)
            {
                sb.AppendLine($$"""
                        Cache<{{type.Name}}>.Serializer = {{type.Name}}WebFormatter.Instance;
                """);
            }

            sb.AppendLine("""
                }
            """);

            foreach (var type in providerType.TargetTypes)
            {
                sb.AppendLine($$"""

                    internal sealed class {{type.Name}}WebFormatter : IWebSerializer<{{type.Name}}>
                    {
                        public static IWebSerializer<{{type.Name}}> Instance { get; } = new {{type.Name}}WebFormatter();

                        public void Serialize(ref WebSerializerWriter writer, {{type.Name}} value, WebSerializerOptions options)
                        {
                """);

                if (type.Prefix is string prefix)
                {
                    var encodedPrefix = UrlEncoder.Default.Encode(prefix);
                    sb.Append($$"""
                            ref var namePrefix = ref GetNamePrefix(ref writer);
                            var originalNamePrefix = namePrefix;
                            if (originalNamePrefix == null)
                            {
                                namePrefix = "{{encodedPrefix}}";
                            }
                            else
                            {
                                namePrefix = originalNamePrefix + "{{encodedPrefix}}";
                            }

                            """);
                }

                int i = 0;
                foreach (var member in type.Members)
                {
                    if (member.IsNullable)
                    {
                        sb.Append(/* lang=c#-test */ $$"""
                            if ({{member.ValueAccess}} is not null)
                            {

                            """);
                    }

                    // NOTE: Cysharp/WebSerializer#23
                    if (0 < i)
                    {
                        sb.Append(/* lang=c#-test */ """
                                        writer.AppendConcatenate();

                            """);
                    }

                    sb.Append($$"""
                                    writer.AppendNamePrefix();
                                    writer.AppendRaw("{{UrlEncoder.Default.Encode(member.SerializedName)}}=");

                        """);
                    if (member.WebSerializer is null)
                    {
                        sb.Append($$"""
                                    options.GetRequiredSerializer<{{member.Type}}>().Serialize(ref writer, {{member.ValueAccess}}, options);

                        """);
                    }
                    else
                    {
                        sb.Append($$"""
                                    new {{member.WebSerializer}}().Serialize(ref writer, {{member.ValueAccess}}, options);

                        """);
                    }

                    if (member.IsNullable)
                    {
                        sb.Append(/* lang=c#-test */ """
                            }

                            """);
                    }

                    i++;
                }

                if (type.Prefix is not null)
                {
                    sb.Append(/* lang=c#-test */ """

                            namePrefix = originalNamePrefix;

                            """);
                }
                sb.AppendLine("""
                            }
                    """);

                if (type.Prefix is not null)
                {
                    sb.AppendLine(/* lang=c#-test */ """

                                [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "namePrefix")]
                                private static extern ref string? GetNamePrefix(ref WebSerializerWriter writer);
                        """);
                }

                foreach (var member in type.Members)
                {
                    if (member.GetterAccessor is not null)
                    {
                        var accessor = member.GetterAccessor;
                        sb.AppendLine($$"""

                                    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = "{{accessor.MetadataName}}")]
                                    private static extern {{accessor.ReturnType}} {{accessor.Name}}({{accessor.RefModifier}}{{accessor.ParameterType}} value);
                            """);
                    }
                }

                sb.AppendLine("""
                        }
                    """);
            }

            sb.AppendLine("""
                }
                """);

            foreach (var _ in providerType.Parents)
            {
                sb.AppendLine($$"""
                    }
                    """);
            }

            var fullType = providerType.FullyQualifiedName
                .Replace("global::", "")
                .Replace("<", "_")
                .Replace(">", "_");
            context.AddSource($"{fullType}.WebSerializable.g.cs", sb.ToString());
        });
    }
}
